package main

var catalog = map[string]map[Lang]string{
	"flag.top": {
		LangTR: "Her seviyede yalnızca en büyük N öğeyi göster (0 = hepsi)",
		LangEN: "Show only the largest N items per level (0 = all)",
		LangDE: "Nur die größten N Einträge pro Ebene zeigen (0 = alle)",
		LangFR: "Afficher seulement les N plus gros éléments par niveau (0 = tous)",
		LangES: "Mostrar solo los N elementos más grandes por nivel (0 = todos)",
		LangIT: "Mostra solo i N elementi più grandi per livello (0 = tutti)",
		LangPT: "Mostrar apenas os N maiores itens por nível (0 = todos)",
		LangRU: "Показывать только N крупнейших элементов на уровне (0 = все)",
		LangZH: "每层仅显示最大的 N 项（0 = 全部）",
		LangJA: "各階層で最大 N 件のみ表示（0 = すべて）",
	},
	"flag.depth": {
		LangTR: "Gösterilecek iç içe seviye sayısı (0 = sınırsız)",
		LangEN: "Number of nested levels to show (0 = unlimited)",
		LangDE: "Anzahl verschachtelter Ebenen (0 = unbegrenzt)",
		LangFR: "Nombre de niveaux imbriqués à afficher (0 = illimité)",
		LangES: "Número de niveles anidados a mostrar (0 = ilimitado)",
		LangIT: "Numero di livelli annidati da mostrare (0 = illimitato)",
		LangPT: "Número de níveis aninhados a mostrar (0 = ilimitado)",
		LangRU: "Число вложенных уровней (0 = без ограничений)",
		LangZH: "显示的嵌套层级数（0 = 无限）",
		LangJA: "表示するネスト階層数（0 = 無制限）",
	},
	"flag.all": {
		LangTR: "Gizli dosyaları (. ile başlayan) dahil et",
		LangEN: "Include hidden files (starting with .)",
		LangDE: "Versteckte Dateien einbeziehen (mit . beginnend)",
		LangFR: "Inclure les fichiers cachés (commençant par .)",
		LangES: "Incluir archivos ocultos (que empiezan con .)",
		LangIT: "Includi i file nascosti (che iniziano con .)",
		LangPT: "Incluir arquivos ocultos (começando com .)",
		LangRU: "Включать скрытые файлы (начинающиеся с .)",
		LangZH: "包含隐藏文件（以 . 开头）",
		LangJA: "隠しファイル（. で始まる）も含める",
	},
	"flag.exclude": {
		LangTR: "Atlanacak dizin/dosya adları (virgülle ayrılmış)",
		LangEN: "Directory/file names to skip (comma-separated)",
		LangDE: "Zu überspringende Ordner-/Dateinamen (kommagetrennt)",
		LangFR: "Noms de dossiers/fichiers à ignorer (séparés par des virgules)",
		LangES: "Nombres de carpetas/archivos a omitir (separados por comas)",
		LangIT: "Nomi di cartelle/file da saltare (separati da virgole)",
		LangPT: "Nomes de pastas/arquivos a ignorar (separados por vírgula)",
		LangRU: "Имена папок/файлов для пропуска (через запятую)",
		LangZH: "要跳过的目录/文件名（用逗号分隔）",
		LangJA: "スキップするフォルダ/ファイル名（カンマ区切り）",
	},
	"flag.json": {
		LangTR: "Sonucu JSON olarak yazdır",
		LangEN: "Print result as JSON",
		LangDE: "Ergebnis als JSON ausgeben",
		LangFR: "Afficher le résultat en JSON",
		LangES: "Imprimir el resultado como JSON",
		LangIT: "Stampa il risultato in JSON",
		LangPT: "Imprimir o resultado como JSON",
		LangRU: "Вывести результат в формате JSON",
		LangZH: "以 JSON 格式输出结果",
		LangJA: "結果を JSON で出力",
	},
	"flag.sort": {
		LangTR: "Sıralama ölçütü: size, name, count",
		LangEN: "Sort by: size, name, count",
		LangDE: "Sortieren nach: size, name, count",
		LangFR: "Trier par : size, name, count",
		LangES: "Ordenar por: size, name, count",
		LangIT: "Ordina per: size, name, count",
		LangPT: "Ordenar por: size, name, count",
		LangRU: "Сортировка: size, name, count",
		LangZH: "排序方式：size、name、count",
		LangJA: "並び替え: size, name, count",
	},
	"flag.reverse": {
		LangTR: "Sıralamayı ters çevir",
		LangEN: "Reverse the sort order",
		LangDE: "Sortierreihenfolge umkehren",
		LangFR: "Inverser l'ordre de tri",
		LangES: "Invertir el orden",
		LangIT: "Inverti l'ordine",
		LangPT: "Inverter a ordem",
		LangRU: "Обратный порядок сортировки",
		LangZH: "反转排序顺序",
		LangJA: "並び順を逆にする",
	},
	"flag.unit": {
		LangTR: "Boyut birimi: auto, b, kb, mb, gb, tb",
		LangEN: "Size unit: auto, b, kb, mb, gb, tb",
		LangDE: "Größeneinheit: auto, b, kb, mb, gb, tb",
		LangFR: "Unité de taille : auto, b, kb, mb, gb, tb",
		LangES: "Unidad de tamaño: auto, b, kb, mb, gb, tb",
		LangIT: "Unità di dimensione: auto, b, kb, mb, gb, tb",
		LangPT: "Unidade de tamanho: auto, b, kb, mb, gb, tb",
		LangRU: "Единица размера: auto, b, kb, mb, gb, tb",
		LangZH: "大小单位：auto、b、kb、mb、gb、tb",
		LangJA: "サイズ単位: auto, b, kb, mb, gb, tb",
	},
	"flag.min": {
		LangTR: "Bu boyutun altındaki öğeleri gizle (ör. 10mb)",
		LangEN: "Hide items below this size (e.g. 10mb)",
		LangDE: "Einträge unter dieser Größe ausblenden (z. B. 10mb)",
		LangFR: "Masquer les éléments sous cette taille (ex. 10mb)",
		LangES: "Ocultar elementos por debajo de este tamaño (p. ej. 10mb)",
		LangIT: "Nascondi gli elementi sotto questa dimensione (es. 10mb)",
		LangPT: "Ocultar itens abaixo deste tamanho (ex. 10mb)",
		LangRU: "Скрыть элементы меньше этого размера (напр. 10mb)",
		LangZH: "隐藏小于此大小的项（例如 10mb）",
		LangJA: "このサイズ未満の項目を隠す（例: 10mb）",
	},
	"flag.tui": {
		LangTR: "İnteraktif gezgini başlat (ok tuşlarıyla gezin)",
		LangEN: "Launch interactive browser (navigate with arrows)",
		LangDE: "Interaktiven Browser starten (mit Pfeiltasten navigieren)",
		LangFR: "Lancer l'explorateur interactif (naviguer avec les flèches)",
		LangES: "Iniciar el explorador interactivo (navegar con flechas)",
		LangIT: "Avvia l'esploratore interattivo (naviga con le frecce)",
		LangPT: "Iniciar o explorador interativo (navegue com as setas)",
		LangRU: "Запустить интерактивный обозреватель (стрелки для навигации)",
		LangZH: "启动交互式浏览器（用方向键导航）",
		LangJA: "対話型ブラウザを起動（矢印キーで移動）",
	},
	"flag.follow": {
		LangTR: "Sembolik bağları takip et (döngü korumalı)",
		LangEN: "Follow symlinks (loop-safe)",
		LangDE: "Symlinks folgen (schleifensicher)",
		LangFR: "Suivre les liens symboliques (protégé contre les boucles)",
		LangES: "Seguir enlaces simbólicos (a prueba de bucles)",
		LangIT: "Segui i collegamenti simbolici (protetto dai cicli)",
		LangPT: "Seguir links simbólicos (protegido contra loops)",
		LangRU: "Переходить по символьным ссылкам (без зацикливания)",
		LangZH: "跟随符号链接（防循环）",
		LangJA: "シンボリックリンクをたどる（ループ対策あり）",
	},
	"flag.disk": {
		LangTR: "Mantıksal boyut yerine diskte ayrılan yeri hesapla (du gibi)",
		LangEN: "Use allocated disk space instead of logical size (like du)",
		LangDE: "Belegten Speicher statt logischer Größe verwenden (wie du)",
		LangFR: "Utiliser l'espace disque alloué au lieu de la taille logique (comme du)",
		LangES: "Usar el espacio en disco asignado en lugar del tamaño lógico (como du)",
		LangIT: "Usa lo spazio su disco allocato invece della dimensione logica (come du)",
		LangPT: "Usar o espaço em disco alocado em vez do tamanho lógico (como du)",
		LangRU: "Использовать занятое место на диске вместо логического размера (как du)",
		LangZH: "使用磁盘实际占用空间而非逻辑大小（类似 du）",
		LangJA: "論理サイズではなくディスク割当量を使用（du 相当）",
	},
	"flag.nocolor": {
		LangTR: "Renkli çıktıyı kapat",
		LangEN: "Disable colored output",
		LangDE: "Farbige Ausgabe deaktivieren",
		LangFR: "Désactiver la sortie en couleur",
		LangES: "Desactivar la salida en color",
		LangIT: "Disabilita l'output a colori",
		LangPT: "Desativar a saída colorida",
		LangRU: "Отключить цветной вывод",
		LangZH: "禁用彩色输出",
		LangJA: "カラー出力を無効にする",
	},
	"flag.verbose": {
		LangTR: "Erişilemeyen yolları listele",
		LangEN: "List inaccessible paths",
		LangDE: "Nicht zugängliche Pfade auflisten",
		LangFR: "Lister les chemins inaccessibles",
		LangES: "Listar rutas inaccesibles",
		LangIT: "Elenca i percorsi inaccessibili",
		LangPT: "Listar caminhos inacessíveis",
		LangRU: "Показать недоступные пути",
		LangZH: "列出无法访问的路径",
		LangJA: "アクセスできないパスを一覧表示",
	},
	"flag.types": {
		LangTR: "Dosya türü (uzantı) bazlı boyut dökümü göster",
		LangEN: "Show size breakdown by file type (extension)",
		LangDE: "Größenaufschlüsselung nach Dateityp (Endung) anzeigen",
		LangFR: "Afficher la répartition des tailles par type de fichier (extension)",
		LangES: "Mostrar el desglose de tamaño por tipo de archivo (extensión)",
		LangIT: "Mostra la ripartizione delle dimensioni per tipo di file (estensione)",
		LangPT: "Mostrar a distribuição de tamanho por tipo de arquivo (extensão)",
		LangRU: "Показать распределение размера по типам файлов (расширениям)",
		LangZH: "按文件类型（扩展名）显示大小分布",
		LangJA: "ファイル種別（拡張子）ごとのサイズ内訳を表示",
	},
	"flag.lang": {
		LangTR: "Arayüz dili (sadece bu komut)",
		LangEN: "Interface language (this command only)",
		LangDE: "Oberflächensprache (nur dieser Befehl)",
		LangFR: "Langue de l'interface (cette commande uniquement)",
		LangES: "Idioma de la interfaz (solo este comando)",
		LangIT: "Lingua dell'interfaccia (solo questo comando)",
		LangPT: "Idioma da interface (apenas este comando)",
		LangRU: "Язык интерфейса (только эта команда)",
		LangZH: "界面语言（仅本次命令）",
		LangJA: "表示言語（このコマンドのみ）",
	},
	"flag.version": {
		LangTR: "Sürümü göster ve çık",
		LangEN: "Show version and exit",
		LangDE: "Version anzeigen und beenden",
		LangFR: "Afficher la version et quitter",
		LangES: "Mostrar la versión y salir",
		LangIT: "Mostra la versione ed esci",
		LangPT: "Mostrar a versão e sair",
		LangRU: "Показать версию и выйти",
		LangZH: "显示版本并退出",
		LangJA: "バージョンを表示して終了",
	},
	"flag.setlang": {
		LangTR: "Dili KALICI ayarla ve çık",
		LangEN: "Set language PERMANENTLY and exit",
		LangDE: "Sprache DAUERHAFT festlegen und beenden",
		LangFR: "Définir la langue de façon PERMANENTE et quitter",
		LangES: "Establecer el idioma de forma PERMANENTE y salir",
		LangIT: "Imposta la lingua in modo PERMANENTE ed esci",
		LangPT: "Definir o idioma PERMANENTEMENTE e sair",
		LangRU: "Задать язык ПОСТОЯННО и выйти",
		LangZH: "永久设置语言并退出",
		LangJA: "言語を恒久的に設定して終了",
	},

	"usage.tagline": {
		LangTR: "diskus — klasör boyutu analiz aracı",
		LangEN: "diskus — folder size analyzer",
		LangDE: "diskus — Ordnergrößen-Analyzer",
		LangFR: "diskus — analyseur de taille de dossiers",
		LangES: "diskus — analizador de tamaño de carpetas",
		LangIT: "diskus — analizzatore di dimensioni di cartelle",
		LangPT: "diskus — analisador de tamanho de pastas",
		LangRU: "diskus — анализатор размера папок",
		LangZH: "diskus — 文件夹大小分析工具",
		LangJA: "diskus — フォルダサイズ分析ツール",
	},
	"usage.usage": {
		LangTR: "\nKullanım:", LangEN: "\nUsage:", LangDE: "\nVerwendung:",
		LangFR: "\nUtilisation :", LangES: "\nUso:", LangIT: "\nUso:",
		LangPT: "\nUso:", LangRU: "\nИспользование:", LangZH: "\n用法：", LangJA: "\n使い方:",
	},
	"usage.usageline": {
		LangTR: "  diskus [seçenekler] [yol]",
		LangEN: "  diskus [options] [path]",
		LangDE: "  diskus [Optionen] [Pfad]",
		LangFR: "  diskus [options] [chemin]",
		LangES: "  diskus [opciones] [ruta]",
		LangIT: "  diskus [opzioni] [percorso]",
		LangPT: "  diskus [opções] [caminho]",
		LangRU: "  diskus [опции] [путь]",
		LangZH: "  diskus [选项] [路径]",
		LangJA: "  diskus [オプション] [パス]",
	},
	"usage.options": {
		LangTR: "\nSeçenekler:", LangEN: "\nOptions:", LangDE: "\nOptionen:",
		LangFR: "\nOptions :", LangES: "\nOpciones:", LangIT: "\nOpzioni:",
		LangPT: "\nOpções:", LangRU: "\nОпции:", LangZH: "\n选项：", LangJA: "\nオプション:",
	},
	"usage.examples": {
		LangTR: "\nÖrnekler:", LangEN: "\nExamples:", LangDE: "\nBeispiele:",
		LangFR: "\nExemples :", LangES: "\nEjemplos:", LangIT: "\nEsempi:",
		LangPT: "\nExemplos:", LangRU: "\nПримеры:", LangZH: "\n示例：", LangJA: "\n例:",
	},
	"usage.ex.depth0": {
		LangTR: "  diskus --depth 0 .   # sınırsız derinlik",
		LangEN: "  diskus --depth 0 .   # unlimited depth",
		LangDE: "  diskus --depth 0 .   # unbegrenzte Tiefe",
		LangFR: "  diskus --depth 0 .   # profondeur illimitée",
		LangES: "  diskus --depth 0 .   # profundidad ilimitada",
		LangIT: "  diskus --depth 0 .   # profondità illimitata",
		LangPT: "  diskus --depth 0 .   # profundidade ilimitada",
		LangRU: "  diskus --depth 0 .   # без ограничения глубины",
		LangZH: "  diskus --depth 0 .   # 无限深度",
		LangJA: "  diskus --depth 0 .   # 深さ無制限",
	},
	"usage.ex.setlang": {
		LangTR: "  diskus --set-lang en   # dili kalıcı ayarla",
		LangEN: "  diskus --set-lang en   # set language permanently",
		LangDE: "  diskus --set-lang en   # Sprache dauerhaft festlegen",
		LangFR: "  diskus --set-lang en   # définir la langue de façon permanente",
		LangES: "  diskus --set-lang en   # establecer el idioma de forma permanente",
		LangIT: "  diskus --set-lang en   # imposta la lingua in modo permanente",
		LangPT: "  diskus --set-lang en   # definir o idioma permanentemente",
		LangRU: "  diskus --set-lang en   # задать язык постоянно",
		LangZH: "  diskus --set-lang en   # 永久设置语言",
		LangJA: "  diskus --set-lang en   # 言語を恒久的に設定",
	},

	"err.prefix": {
		LangTR: "Hata: ", LangEN: "Error: ", LangDE: "Fehler: ", LangFR: "Erreur : ",
		LangES: "Error: ", LangIT: "Errore: ", LangPT: "Erro: ", LangRU: "Ошибка: ",
		LangZH: "错误：", LangJA: "エラー: ",
	},
	"err.invalidlang": {
		LangTR: "geçersiz dil: %q",
		LangEN: "invalid language: %q",
		LangDE: "ungültige Sprache: %q",
		LangFR: "langue invalide : %q",
		LangES: "idioma no válido: %q",
		LangIT: "lingua non valida: %q",
		LangPT: "idioma inválido: %q",
		LangRU: "неверный язык: %q",
		LangZH: "无效的语言：%q",
		LangJA: "無効な言語: %q",
	},
	"err.tui": {
		LangTR: "TUI hatası: ", LangEN: "TUI error: ", LangDE: "TUI-Fehler: ",
		LangFR: "Erreur TUI : ", LangES: "Error de TUI: ", LangIT: "Errore TUI: ",
		LangPT: "Erro de TUI: ", LangRU: "Ошибка TUI: ", LangZH: "TUI 错误：", LangJA: "TUI エラー: ",
	},
	"err.json": {
		LangTR: "JSON hatası:", LangEN: "JSON error:", LangDE: "JSON-Fehler:",
		LangFR: "Erreur JSON :", LangES: "Error de JSON:", LangIT: "Errore JSON:",
		LangPT: "Erro de JSON:", LangRU: "Ошибка JSON:", LangZH: "JSON 错误：", LangJA: "JSON エラー:",
	},
	"err.inaccessible": {
		LangTR: "Erişilemeyen %d öğe:",
		LangEN: "%d inaccessible items:",
		LangDE: "%d nicht zugängliche Einträge:",
		LangFR: "%d éléments inaccessibles :",
		LangES: "%d elementos inaccesibles:",
		LangIT: "%d elementi inaccessibili:",
		LangPT: "%d itens inacessíveis:",
		LangRU: "%d недоступных элементов:",
		LangZH: "%d 个无法访问的项：",
		LangJA: "アクセスできない項目が %d 件:",
	},
	"err.more": {
		LangTR: "  … +%d tane daha",
		LangEN: "  … +%d more",
		LangDE: "  … +%d weitere",
		LangFR: "  … +%d de plus",
		LangES: "  … +%d más",
		LangIT: "  … +%d in più",
		LangPT: "  … +%d a mais",
		LangRU: "  … +%d ещё",
		LangZH: "  … 还有 +%d 个",
		LangJA: "  … 他 +%d 件",
	},
	"scan.progress": {
		LangTR: "\r%s taranıyor… %d öğe",
		LangEN: "\r%s scanning… %d items",
		LangDE: "\r%s scanne… %d Einträge",
		LangFR: "\r%s analyse… %d éléments",
		LangES: "\r%s escaneando… %d elementos",
		LangIT: "\r%s scansione… %d elementi",
		LangPT: "\r%s escaneando… %d itens",
		LangRU: "\r%s сканирование… %d элементов",
		LangZH: "\r%s 扫描中… %d 项",
		LangJA: "\r%s スキャン中… %d 件",
	},
	"setlang.savefail": {
		LangTR: "Ayar kaydedilemedi: ",
		LangEN: "Could not save config: ",
		LangDE: "Konfiguration konnte nicht gespeichert werden: ",
		LangFR: "Impossible d'enregistrer la configuration : ",
		LangES: "No se pudo guardar la configuración: ",
		LangIT: "Impossibile salvare la configurazione: ",
		LangPT: "Não foi possível salvar a configuração: ",
		LangRU: "Не удалось сохранить настройки: ",
		LangZH: "无法保存配置：",
		LangJA: "設定を保存できませんでした: ",
	},
	"setlang.auto": {
		LangTR: "Dil sistem diline ayarlandı.",
		LangEN: "Language set to system default.",
		LangDE: "Sprache auf Systemstandard gesetzt.",
		LangFR: "Langue définie sur celle du système.",
		LangES: "Idioma establecido al del sistema.",
		LangIT: "Lingua impostata su quella di sistema.",
		LangPT: "Idioma definido para o do sistema.",
		LangRU: "Язык установлен на системный.",
		LangZH: "语言已设置为系统默认。",
		LangJA: "言語をシステム既定に設定しました。",
	},
	"setlang.done": {
		LangTR: "Dil kalıcı olarak ayarlandı: %s",
		LangEN: "Language set permanently: %s",
		LangDE: "Sprache dauerhaft festgelegt: %s",
		LangFR: "Langue définie de façon permanente : %s",
		LangES: "Idioma establecido de forma permanente: %s",
		LangIT: "Lingua impostata in modo permanente: %s",
		LangPT: "Idioma definido permanentemente: %s",
		LangRU: "Язык задан постоянно: %s",
		LangZH: "语言已永久设置：%s",
		LangJA: "言語を恒久的に設定しました: %s",
	},
	"setlang.configfile": {
		LangTR: "Ayar dosyası: ",
		LangEN: "Config file: ",
		LangDE: "Konfigurationsdatei: ",
		LangFR: "Fichier de configuration : ",
		LangES: "Archivo de configuración: ",
		LangIT: "File di configurazione: ",
		LangPT: "Arquivo de configuração: ",
		LangRU: "Файл настроек: ",
		LangZH: "配置文件：",
		LangJA: "設定ファイル: ",
	},

	"render.empty": {
		LangTR: "  (boş dizin)", LangEN: "  (empty directory)", LangDE: "  (leeres Verzeichnis)",
		LangFR: "  (répertoire vide)", LangES: "  (directorio vacío)", LangIT: "  (directory vuota)",
		LangPT: "  (diretório vazio)", LangRU: "  (пустой каталог)", LangZH: "  （空目录）", LangJA: "  （空のディレクトリ）",
	},
	"render.total": {
		LangTR: "Toplam:", LangEN: "Total:", LangDE: "Gesamt:", LangFR: "Total :",
		LangES: "Total:", LangIT: "Totale:", LangPT: "Total:", LangRU: "Всего:",
		LangZH: "总计：", LangJA: "合計:",
	},
	"render.files": {
		LangTR: "(%d dosya)", LangEN: "(%d files)", LangDE: "(%d Dateien)", LangFR: "(%d fichiers)",
		LangES: "(%d archivos)", LangIT: "(%d file)", LangPT: "(%d arquivos)", LangRU: "(%d файлов)",
		LangZH: "（%d 个文件）", LangJA: "（%d 件）",
	},
	"render.inacc_warn": {
		LangTR: "  ⚠ %d öğe erişilemedi (izin/atlanan)",
		LangEN: "  ⚠ %d items inaccessible (permission/skipped)",
		LangDE: "  ⚠ %d Einträge nicht zugänglich (Berechtigung/übersprungen)",
		LangFR: "  ⚠ %d éléments inaccessibles (permission/ignorés)",
		LangES: "  ⚠ %d elementos inaccesibles (permiso/omitidos)",
		LangIT: "  ⚠ %d elementi inaccessibili (permessi/saltati)",
		LangPT: "  ⚠ %d itens inacessíveis (permissão/ignorados)",
		LangRU: "  ⚠ недоступно элементов: %d (нет прав/пропущено)",
		LangZH: "  ⚠ %d 个项无法访问（权限/已跳过）",
		LangJA: "  ⚠ %d 件にアクセスできません（権限/スキップ）",
	},
	"render.more_items": {
		LangTR: "… +%d öğe daha", LangEN: "… +%d more items", LangDE: "… +%d weitere Einträge",
		LangFR: "… +%d éléments de plus", LangES: "… +%d elementos más", LangIT: "… +%d elementi in più",
		LangPT: "… +%d itens a mais", LangRU: "… +%d ещё", LangZH: "… 还有 +%d 项", LangJA: "… 他 +%d 件",
	},

	"types.noext": {
		LangTR: "(uzantısız)", LangEN: "(no extension)", LangDE: "(ohne Endung)",
		LangFR: "(sans extension)", LangES: "(sin extensión)", LangIT: "(senza estensione)",
		LangPT: "(sem extensão)", LangRU: "(без расширения)", LangZH: "（无扩展名）", LangJA: "（拡張子なし）",
	},
	"types.title": {
		LangTR: " — dosya türü dökümü", LangEN: " — file type breakdown", LangDE: " — Aufschlüsselung nach Dateityp",
		LangFR: " — répartition par type de fichier", LangES: " — desglose por tipo de archivo",
		LangIT: " — ripartizione per tipo di file", LangPT: " — distribuição por tipo de arquivo",
		LangRU: " — распределение по типам файлов", LangZH: " — 文件类型分布", LangJA: " — ファイル種別の内訳",
	},
	"types.nofiles": {
		LangTR: "  (dosya yok)", LangEN: "  (no files)", LangDE: "  (keine Dateien)",
		LangFR: "  (aucun fichier)", LangES: "  (sin archivos)", LangIT: "  (nessun file)",
		LangPT: "  (sem arquivos)", LangRU: "  (нет файлов)", LangZH: "  （无文件）", LangJA: "  （ファイルなし）",
	},
	"types.files": {
		LangTR: "%d dosya", LangEN: "%d files", LangDE: "%d Dateien", LangFR: "%d fichiers",
		LangES: "%d archivos", LangIT: "%d file", LangPT: "%d arquivos", LangRU: "%d файлов",
		LangZH: "%d 个文件", LangJA: "%d 件",
	},
	"types.more_types": {
		LangTR: "  … +%d tür daha", LangEN: "  … +%d more types", LangDE: "  … +%d weitere Typen",
		LangFR: "  … +%d types de plus", LangES: "  … +%d tipos más", LangIT: "  … +%d tipi in più",
		LangPT: "  … +%d tipos a mais", LangRU: "  … +%d ещё типов", LangZH: "  … 还有 +%d 种", LangJA: "  … 他 +%d 種類",
	},
	"types.summary": {
		LangTR: "(%d dosya, %d tür)", LangEN: "(%d files, %d types)", LangDE: "(%d Dateien, %d Typen)",
		LangFR: "(%d fichiers, %d types)", LangES: "(%d archivos, %d tipos)", LangIT: "(%d file, %d tipi)",
		LangPT: "(%d arquivos, %d tipos)", LangRU: "(%d файлов, %d типов)", LangZH: "（%d 个文件，%d 种类型）",
		LangJA: "（%d 件、%d 種類）",
	},

	"tui.files": {
		LangTR: "  (%d dosya)", LangEN: "  (%d files)", LangDE: "  (%d Dateien)", LangFR: "  (%d fichiers)",
		LangES: "  (%d archivos)", LangIT: "  (%d file)", LangPT: "  (%d arquivos)", LangRU: "  (%d файлов)",
		LangZH: "  （%d 个文件）", LangJA: "  （%d 件）",
	},
	"tui.empty": {
		LangTR: "  (boş)\n", LangEN: "  (empty)\n", LangDE: "  (leer)\n", LangFR: "  (vide)\n",
		LangES: "  (vacío)\n", LangIT: "  (vuoto)\n", LangPT: "  (vazio)\n", LangRU: "  (пусто)\n",
		LangZH: "  （空）\n", LangJA: "  （空）\n",
	},
	"tui.footer": {
		LangTR: "↑/↓ gez  •  → gir  •  ← geri  •  q çıkış",
		LangEN: "↑/↓ move  •  → enter  •  ← back  •  q quit",
		LangDE: "↑/↓ bewegen  •  → öffnen  •  ← zurück  •  q beenden",
		LangFR: "↑/↓ déplacer  •  → entrer  •  ← retour  •  q quitter",
		LangES: "↑/↓ mover  •  → entrar  •  ← atrás  •  q salir",
		LangIT: "↑/↓ muovi  •  → entra  •  ← indietro  •  q esci",
		LangPT: "↑/↓ mover  •  → entrar  •  ← voltar  •  q sair",
		LangRU: "↑/↓ выбор  •  → войти  •  ← назад  •  q выход",
		LangZH: "↑/↓ 移动  •  → 进入  •  ← 返回  •  q 退出",
		LangJA: "↑/↓ 移動  •  → 開く  •  ← 戻る  •  q 終了",
	},

	"err.sort": {
		LangTR: "geçersiz sıralama: %q (size/name/count)",
		LangEN: "invalid sort: %q (size/name/count)",
		LangDE: "ungültige Sortierung: %q (size/name/count)",
		LangFR: "tri invalide : %q (size/name/count)",
		LangES: "orden no válido: %q (size/name/count)",
		LangIT: "ordinamento non valido: %q (size/name/count)",
		LangPT: "ordenação inválida: %q (size/name/count)",
		LangRU: "неверная сортировка: %q (size/name/count)",
		LangZH: "无效的排序：%q（size/name/count）",
		LangJA: "無効な並び替え: %q (size/name/count)",
	},
	"err.unit": {
		LangTR: "geçersiz birim: %q (b/kb/mb/gb/tb)",
		LangEN: "invalid unit: %q (b/kb/mb/gb/tb)",
		LangDE: "ungültige Einheit: %q (b/kb/mb/gb/tb)",
		LangFR: "unité invalide : %q (b/kb/mb/gb/tb)",
		LangES: "unidad no válida: %q (b/kb/mb/gb/tb)",
		LangIT: "unità non valida: %q (b/kb/mb/gb/tb)",
		LangPT: "unidade inválida: %q (b/kb/mb/gb/tb)",
		LangRU: "неверная единица: %q (b/kb/mb/gb/tb)",
		LangZH: "无效的单位：%q（b/kb/mb/gb/tb）",
		LangJA: "無効な単位: %q (b/kb/mb/gb/tb)",
	},
	"err.size": {
		LangTR: "geçersiz boyut: %q (ör. 10mb, 1.5g, 500k)",
		LangEN: "invalid size: %q (e.g. 10mb, 1.5g, 500k)",
		LangDE: "ungültige Größe: %q (z. B. 10mb, 1.5g, 500k)",
		LangFR: "taille invalide : %q (ex. 10mb, 1.5g, 500k)",
		LangES: "tamaño no válido: %q (p. ej. 10mb, 1.5g, 500k)",
		LangIT: "dimensione non valida: %q (es. 10mb, 1.5g, 500k)",
		LangPT: "tamanho inválido: %q (ex. 10mb, 1.5g, 500k)",
		LangRU: "неверный размер: %q (напр. 10mb, 1.5g, 500k)",
		LangZH: "无效的大小：%q（例如 10mb、1.5g、500k）",
		LangJA: "無効なサイズ: %q (例: 10mb, 1.5g, 500k)",
	},
}
